name: 0.1$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: build
    arguments: "-c Release"
    workingDirectory: src
  displayName: 'Build .NET Core Solution'
  
- task: DotNetCoreCLI@2
  inputs:
    command: test
    arguments: '-c Release'
    nobuild: true
    versioningScheme: byBuildNumber
    workingDirectory: src
  displayName: 'Test .NET Core Solution'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    arguments: "-c Release /p:PackageVersion=$(Build.BuildNumber) Lindemann.Analyzers\Lindemann.Analyzers.csproj"
    nobuild: true
    workingDirectory: src
    packDirectory: '$(Build.ArtifactStagingDirectory)' 
  displayName: 'Pack Lindemann.Analyzers'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'Lindemann.Analyzers'
  displayName: 'Publish Build Artifacts'
